### PR TITLE
Bug/302 filter pattern values not updated in job

### LINKED ISSUE #302: String pattern filter does not see an update of the pattern.
1) Create a job with a String pattern filter.
2) Run the job.
3) Go to More -> String patterns and edit the pattern
4) Run the same job.

Expected output:
The results of the filter are going to be different as the string pattern has changed

Actual output:
The filter did not see that the pattern has changed and works on the old version - same results as during the first run.

5) Save and close the job.
6) Load the job again.
7) Run the job to see the updated results.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #302 

Fixes: 
- Filter pattern
- Simple dictionary
- Synonym catalog

An interface "ReferenceDataChangeListener" is implemented to signal that a dictionary or string pattern has been edited. 

The redundant listeners have been kept so that no extension is broken.

### CODE REVIEW

**Comment by LosD** [comment]
Failed travis build seems unrelated

File: desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java [hunk 1]
```diff
@@ -167,18 +177,49 @@ public void removeDictionary(Dictionary dict, boolean externalize) {
...
     public void addStringPattern(StringPattern sp, boolean externalize) {
+        addStringPatternHelper(sp, externalize);
+        for (StringPatternChangeListener listener : _stringPatternListeners) {
+            listener.onAdd(sp);
+        }
+        for(ReferenceDataChangeListener<StringPattern> listener : _stringPatternV2Listeners){
+            listener.onAdd(sp);
+        }
+    }
+    private void addStringPatternHelper(StringPattern sp, boolean externalize) {
```
Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java]: Same here with the helper/internal naming.

File: desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java [hunk 2]
```diff
@@ -167,18 +177,49 @@ public void removeDictionary(Dictionary dict, boolean externalize) {
...
+            if (externalize) {
+                _configurationWriter.removeDictionary(oldDictionary.getName());
+                _userPreferences.save();
+            }
+        }
+        
+        addDictionaryHelper(newDictionary, externalize);
+        for(ReferenceDataChangeListener<Dictionary> listener : _dictionaryV2Listeners){
+            listener.onChange(oldDictionary, newDictionary);
+        }
```
Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java]: Isn't this missing an update (remove+add) of the old-style listeners, or is that handled somewhere else (this goes for the string pattern as well).

**Comment by LosD** [comment]
In general looks very good. How hard would it be to extend to synonym catalogs as well? They don't really have the same issue, AFAIK, but it would be nice to be consistent across all reference data (both in programming model, but also to be sure they behave in the same way).

**Comment by LosD** [comment]
Testing now

**Comment by ClaudiaPHI** [comment]
It should not be difficult to change for synonyms as well.

**Comment by LosD** [comment]
A bit of a weird issue for String pattern: If I change the pattern, and use the test inputs, I get this exception when clicking "Save Pattern":
```
Unexpected error!
 

Message:
    java.lang.IllegalArgumentException: StringPattern name 'DennisTest' is not unique!
Level:
    SEVERE
Stack Trace:
StringPattern name 'DennisTest' is not unique!
    org.datacleaner.user.MutableReferenceDataCatalog.addStringPatternInternal(MutableReferenceDataCatalog.java:230)
    org.datacleaner.user.MutableReferenceDataCatalog.changeStringPattern(MutableReferenceDataCatalog.java:279)
    org.datacleaner.user.MutableReferenceDataCatalog.changeStringPattern(MutableReferenceDataCatalog.java:266)
    org.datacleaner.windows.SimpleStringPatternDialog$3.actionPerformed(SimpleStringPatternDialog.java:162)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    java.awt.Component.processMouseEvent(Component.java:6533)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6298)
    java.awt.Container.processEvent(Container.java:2236)
    java.awt.Component.dispatchEventImpl(Component.java:4889)
    java.awt.Container.dispatchEventImpl(Container.java:2294)
    java.awt.Component.dispatchEvent(Component.java:4711)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    java.awt.Container.dispatchEventImpl(Container.java:2280)
    java.awt.Window.dispatchEventImpl(Window.java:2746)
    java.awt.Component.dispatchEvent(Component.java:4711)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:709)
    java.awt.EventQueue$3.run(EventQueue.java:703)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:731)
    java.awt.EventQueue$4.run(EventQueue.java:729)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LosD** [comment]
Remove dictionary matches component still seems to lose its connections when changing dictionary

**Comment by LosD** [comment]
All other components seems to work perfectly

File: desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java [hunk 3]
```diff
@@ -46,8 +46,11 @@
     private static final long serialVersionUID = 1L;
 
     private final List<DictionaryChangeListener> _dictionaryListeners = new ArrayList<>();
+    private final List<ReferenceDataChangeListener<Dictionary>> _dictionaryV2Listeners = new ArrayList<>();
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java]: I really don't like the V2 in the field name, maybe call it _dictionaryChangeListeners instead. The same goes for the two new fields right below.

**Comment by arjansh** [comment]
Some general remarks regarding the MutableReferenceDataCatalog class:
- Can you add a @SuppressWarnings("deprecation") annotation to the class? It contains a lot of references to deprecated classes.
- Can you also add @Deprecated annotations to the add and remove methods for the old listener interfaces?

File: desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java [hunk 4]
```diff
@@ -213,13 +257,41 @@ public void removeStringPattern(StringPattern sp, boolean externalize) {
...
         }
     }
 
+    public void changeStringPattern(StringPattern oldPattern, StringPattern newPattern){
+        changeStringPattern(oldPattern, newPattern, true);
+    }
+    
+    public void changeStringPattern(StringPattern oldPattern, StringPattern newPattern, boolean externalize){
+        // The old reference is removed from user preferences and we add a new
+        // patern with the same name but with a
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/user/MutableReferenceDataCatalog.java]: patern should be pattern (and the comment line below can be appended to this one).

**Comment by arjansh** [comment]
The SingleStringPatternPropertyWidget class still implements the now deprecated StringPatternChangeListener, can it be changed so it implements ReferenceDataChangeListener<StringPattern>?

File: desktop/ui/src/main/java/org/datacleaner/widgets/properties/AbstractMultipleCheckboxesPropertyWidget.java [hunk 5]
```diff
@@ -173,6 +173,27 @@ protected JCheckBox addCheckBox(E item, boolean checked) {
...
+        if (checkBox != null) {
+            _checkBoxes.remove(name);
+            checkBox.addListener(CHANGE_LISTENER);
+            final boolean isSelected = checkBox.isSelected();
+            checkBox.setValue(newValue);
+            checkBox.setSelected(isSelected, true);
+            _checkBoxes.put(name, checkBox);
+            add(checkBox);
+            /* 'fireValueChanged' changes the value in the component builder. Otherwise the listener is
+            activated at the later point(when the window is opened again) */
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/widgets/properties/AbstractMultipleCheckboxesPropertyWidget.java]: I personally think that it is a "end of line" style comment fits better here then a block comment.

File: desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleDictionariesPropertyWidget.java [hunk 6]
```diff
@@ -112,4 +112,9 @@ protected String getNotAvailableText() {
 		return "- no dictionaries available -";
 	}
 
+    @Override
+    public void onChange(Dictionary oldReferenceData, Dictionary newreferenceData) {
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleDictionariesPropertyWidget.java]: Maybe change the names of the variable to oldDictionary and newDictionary.

File: desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleSynonymCatalogsPropertyWidget.java [hunk 7]
```diff
@@ -111,4 +111,9 @@ public void onRemove(SynonymCatalog synonymCatalog) {
 	protected String getNotAvailableText() {
 		return "- no synonym catalogs available - ";
 	}
+
+    @Override
+    public void onChange(SynonymCatalog oldReferenceData, SynonymCatalog newReferenceData) {
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleSynonymCatalogsPropertyWidget.java]: Maybe change the names of the parameters to oldCatalog and newCatalog.

File: desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleSynonymCatalogPropertyWidget.java [hunk 8]
```diff
@@ -131,4 +131,14 @@ public void onRemove(SynonymCatalog synonymCatalog) {
 		_comboBox.removeItem(synonymCatalog);
 	}
 
+    @Override
+    public void onChange(SynonymCatalog oldReferenceData, SynonymCatalog newReferenceData) {
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleSynonymCatalogPropertyWidget.java]: Maybe change the names of the parameters to oldCatalog and newCatalog.

File: desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java [hunk 9]
```diff
@@ -306,7 +316,7 @@ protected AnalysisJobBuilderWindowImpl(DataCleanerConfiguration configuration, W
             Provider<ReferenceDataDialog> referenceDataDialogProvider, UsageLogger usageLogger,
             Provider<OptionsDialog> optionsDialogProvider,
             Provider<MonitorConnectionDialog> monitorConnectionDialogProvider,
-            OpenAnalysisJobActionListener openAnalysisJobActionListener, DatabaseDriverCatalog databaseDriverCatalog) {
+            OpenAnalysisJobActionListener openAnalysisJobActionListener, DatabaseDriverCatalog databaseDriverCatalog, MutableReferenceDataCatalog mutableReferenceCatalog) {
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: Line length now exceeds 120 characters.

File: desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java [hunk 10]
```diff
@@ -965,4 +991,4 @@ public UserPreferences getUserPreferences() {
     public DCModule getDCModule() {
         return _dcModule;
     }
-}
+}
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: No newline at end of file.

**Comment by arjansh** [comment]
I'm not particularly happy about the introduced ReferenceDataAnalysisJobWindowImplListeners class. I personally think the it would be better if the listener classes on that class are added to the AnalysisJobBuilderWindowImpl instead, but I think you chose to add them to a separate class because the AnalysisJobBuilderWindowImpl  already is quite large. Maybe they can just be added as separate class instead (extending a base class).

**Comment by arjansh** [comment]
I tested the PR and outside of my comments on the code it seems to fix all problems it intends to fix.

File: desktop/ui/src/main/java/org/datacleaner/widgets/properties/AbstractMultipleCheckboxesPropertyWidget.java [hunk 11]
```diff
@@ -173,6 +173,26 @@ protected JCheckBox addCheckBox(E item, boolean checked) {
...
+        final DCCheckBox<E> checkBox = _checkBoxes.get(name);
+        if (checkBox != null) {
+            _checkBoxes.remove(name);
+            checkBox.addListener(CHANGE_LISTENER);
+            final boolean isSelected = checkBox.isSelected();
+            checkBox.setValue(newValue);
+            checkBox.setSelected(isSelected, true);
+            _checkBoxes.put(name, checkBox);
+            add(checkBox);
+            // 'fireValueChanged' changes the value in the component builder. Otherwise the listener is activated at the later point(when the window is opened again) *
```
Comment (arjansh) [inline desktop/ui/src/main/java/org/datacleaner/widgets/properties/AbstractMultipleCheckboxesPropertyWidget.java]: Now the line is to long. What I meant is something like this:

```
            // 'fireValueChanged' changes the value in the component builder. Otherwise the listener is
            // activated at the later point (when the window is opened again).
```

**Comment by arjansh** [comment]
LGTM!
