### PR TITLE
Bug/360 sort integers version 2

### LINKED ISSUE #360: Sorting in Create CSV and Create Excel works incorrectly for numeric content
In  Create CSV file and Create Excel File it is possible to select a 'Column to be sorted on'  under 'Optional properties'. 
It sorts, but not correctly for numeric input, such as ID's. Numbers are being sorted alphabetically?
ID's had been created by use of DC transformer <Generate ID>.
I even applied transformer Convert to number, but still the same incorrect ordering in output.

Ordering of output is important for tracability / readibility of results,since DC transformers randomize order due to multi-threading.

### PR DESCRIPTION
**Pull request by tomaszguzialek**
Fixes #360 

Fixes case-sensitivity while sorting lexicographically.

### CODE REVIEW

File: components/writers/src/main/java/org/datacleaner/extension/output/SortHelper.java [hunk 1]
```diff
@@ -64,10 +64,12 @@ public int compare(Row row1, Row row2) {
                     for (int i = 0; i < numberOfSelectItems; i++) {
                         final String rowValue1 = (String) row1.getValue(i);
                         final String rowValue2 = (String) row2.getValue(i);
-                        if (CompareUtils.compare(rowValue1, rowValue2) == 0) {
+                        final String rowValue1LowerCased = rowValue1.toLowerCase();
+                        final String rowValue2LowerCased = rowValue2.toLowerCase();
+                        if (CompareUtils.compare(rowValue1LowerCased, rowValue2LowerCased) == 0) {
```
Comment (LosD) [inline components/writers/src/main/java/org/datacleaner/extension/output/SortHelper.java]: If you know they are that and they are Strings, you can just use String.compareToIgnoreCase() instead of lowercasing them.

File: components/writers/src/main/java/org/datacleaner/extension/output/SortHelper.java [hunk 2]
```diff
@@ -64,10 +64,12 @@ public int compare(Row row1, Row row2) {
...
                             continue;
                         } else {
-                            return CompareUtils.compare(rowValue1, rowValue2);
+                            return CompareUtils.compare(rowValue1LowerCased, rowValue2LowerCased);
```
Comment (LosD) [inline components/writers/src/main/java/org/datacleaner/extension/output/SortHelper.java]: This seems a little wasteful. Why not save the value from first compare?

**Comment by LosD** [comment]
Probably a little more expensive time-wise than it needs to be. I'm not sure if it will drown in the I/O, but nevertheless I think it could be better, and the code will be a little easier to read as an added bonus.

File: components/writers/src/test/java/org/datacleaner/extension/output/CreateCsvFileAnalyzerTest.java [hunk 3]
```diff
@@ -204,6 +204,58 @@ public void testSortLexicographic() throws Exception {
...
+            try (DataSet dataSet = dataContext.query().from(targetFilename).selectAll().execute()) {
+                while (dataSet.next()) {
+                    Row row = dataSet.getRow();
+                    String idValue = (String) row.getValue(0);
+                    resultIds.add(idValue);
+                }
+            }
+        }
+
+        assertEquals("[Claudia, claudia, Dennis, dennis, Kasper, kasper, Tomasz, tomasz]", resultIds.toString());
```
Comment (LosD) [inline components/writers/src/test/java/org/datacleaner/extension/output/CreateCsvFileAnalyzerTest.java]: Hehe, I like the use of us! :)

Comment (tomaszguzialek) [inline components/writers/src/test/java/org/datacleaner/extension/output/CreateCsvFileAnalyzerTest.java]: Need to leave some trace for future generations :).

**Comment by tomaszguzialek** [comment]
Adressed the remarks, will merge when Travis is happy.

**Comment by LosD** [comment]
:+1:
