### PR TITLE
Make ImmutableOutputDataStreamJob serializable

### LINKED ISSUE #842: AnalyzerResults produced within an Output Data Streams are not serializable
It seems that when we use output data streams and produce results from components within that stream, then saivng the result fails because of a non-transient reference somewhere to ImmutableAnalysisJob (I bet this is the child job referenced somewhere).

Example job:
image

Error scenario:
image

### PR DESCRIPTION
**Pull request by LosD**
It used to be impossible to serialize jobs with output datastreams, because ImmutableOutputDataStreamJob contains a non-transient reference to AnalysisJob. Making it transient fixes that without breaking the serialized result.

Fixes #842

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM!

File: engine/core/src/test/java/org/datacleaner/test/full/scenarios/JobWithOutputDataStreamsTest.java [hunk 1]
```diff
@@ -146,14 +148,18 @@ public void testSimpleBuildAndExecuteScenario() throws Throwable {
 
         assertEquals(2, resultFuture.getResults().size());
 
+        final byte[] serialized = SerializationUtils.serialize(new SimpleAnalysisResult(resultFuture.getResultMap()));
+
+        SimpleAnalysisResult deSerializedResult = (SimpleAnalysisResult) SerializationUtils.deserialize(serialized);
```
Comment (kaspersorensen) [inline engine/core/src/test/java/org/datacleaner/test/full/scenarios/JobWithOutputDataStreamsTest.java]: final ;-)

Comment (LosD) [inline engine/core/src/test/java/org/datacleaner/test/full/scenarios/JobWithOutputDataStreamsTest.java]: Damn!

**Comment by kaspersorensen** [comment]
Build break is strange, but I cannot see how it can be related. Merge?
