### PR TITLE
Bug/1015 options dialog npe

### LINKED ISSUE #1015: NPE when opening the options dialog
Using current release/5.0 branch, if I click More -> Options, then I get this error:

```
ERROR 22:55:55 DCUncaughtExceptionHandler - Thread AWT-EventQueue-0 threw uncaught exception
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NullPointerException
  at org.datacleaner.windows.OptionsDialog.<init>(OptionsDialog.java:94)
  while locating org.datacleaner.windows.OptionsDialog

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at org.datacleaner.windows.AnalysisJobBuilderWindowImpl$6.actionPerformed(AnalysisJobBuilderWindowImpl.java:912)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$400(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at org.datacleaner.windows.OptionsDialog$RemoteComponentsTab.getRemoteComponentsServer(OptionsDialog.java:602)
        at org.datacleaner.windows.OptionsDialog$RemoteComponentsTab.<init>(OptionsDialog.java:501)
        at org.datacleaner.windows.OptionsDialog.<init>(OptionsDialog.java:107)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.google.inject.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:85)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 39 more
```

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #1015

### CODE REVIEW

File: desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java [hunk 1]
```diff
@@ -19,33 +19,38 @@
...
-import javax.swing.*;
+import javax.swing.JButton;
+import javax.swing.JCheckBox;
+import javax.swing.JComponent;
+import javax.swing.JFileChooser;
+import javax.swing.JLabel;
+import javax.swing.JPanel;
+import javax.swing.JPasswordField;
+import javax.swing.JTextField;
+import javax.swing.Timer;
```
Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java]: I think change this is actually a place where IntelliJ and Eclipse formatters deviate.Eclipse default is 99, while IntelliJ has 5. I've changed mine to 30 at some point to avoid clashes.

However, I also think the the IntelliJ default is superior here; when you import many classes from a package, importing every single package seems a bit silly.

We will probably need to find a standard, changing it back and forth will annoy everyone. What it is isn't super important to me when it is automated anyway.

File: desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java [hunk 2]
```diff
@@ -89,8 +94,8 @@
 
     @Inject
     protected OptionsDialog(WindowContext windowContext, DataCleanerConfiguration configuration,
-                            UserPreferences userPreferences, DatabaseDriversPanel databaseDriversPanel,
-                            ExtensionPackagesPanel extensionPackagesPanel) {
+            UserPreferences userPreferences, DatabaseDriversPanel databaseDriversPanel,
+            ExtensionPackagesPanel extensionPackagesPanel) {
```
Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java]: Another codestyle difference. Didn't we get the Czech team to use the defaults files?

We really need to keep an eye out for these differences so we can harmonize codestyles.

**Comment by LosD** [comment]
Code looks good, except for all the code style differences, though the real issue is in the "old" code, not in yours.
