### PR TITLE
Escape CoalesceUnitConverter, and make de-/serialization symmetric.

### LINKED ISSUE #336: Comma in column name causes coalesce transformation to fail
We are not escaping the comma in the column name while serializing it for the coalesce transformation. It then does not recognize it.

### PR DESCRIPTION
**Pull request by LosD**
Fixes #336

### CODE REVIEW

File: engine/core/src/main/java/org/datacleaner/util/convert/SerializationStringEscaper.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+public class SerializationStringEscaper {
+    private static final String[][] ESCAPE_MAPPING = { { "&amp;", "&" }, { "&#91;", "[" }, { "&#93;", "]" },
+            { "&#44;", "," }, { "&lt;", "<" }, { "&gt;", ">" }, { "&quot;", "\"" }, { "&copy;", "\u00a9" },
+            { "&reg;", "\u00ae" }, { "&euro;", "\u20a0" } };
+    private static final String[][] ESCAPE_MAPPING_REVERSED;
+    
+    // Ughhh.
+    static {
+        ESCAPE_MAPPING_REVERSED = (String[][]) ArrayUtils.clone(ESCAPE_MAPPING);
+        ArrayUtils.reverse(ESCAPE_MAPPING_REVERSED);
```
Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/util/convert/SerializationStringEscaper.java]: I guess if you really have a "Ughhh" feeling we COULD also simply adjust the for-loop to run through the array backwards.

**Comment by kaspersorensen** [comment]
Looks good to me. I will let you decide whether we merge as-is or if you want to do something about the "Ughhh" comment ;-)

**Comment by LosD** [comment]
Nah, that's even more ughhh :) Let's merge!
