### PR TITLE
Issue #1160: Fixed by adding "file://" prefix support in FileResolver

### LINKED ISSUE #1160: SynonymCatalog + Dictionary filenames in conf.xml gets double scheme
There seems to be an issue with the resource path (```<filename>```) of the file-based dictionaries and synonym catalogs in conf.xml when being edited by the desktop dialogs for this.

After saving a synonym catalog, then restarting datacleaner and then editing it again, I get a filename like this:
```
<filename>file://file:/datastores/job_title_synonyms.txt</filename>
```

Note: This particular example is a relative path (datastores/job_title_synonyms.txt) within DataCleanerHome. I have not tried it with an absolute path.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #1160 

Actually the solution is not very pretty because it is a file-only (as in - not any other resource types) fix. But it seems to be the minimum-impact resolution of the bug. The more general issue is that loading of dictionary and synonym resource is using the deprecated ```createFilename(...)``` method on the ```ConfigurationReaderInterceptor```.

It would be better (but a separate issue IMO) to use a real resource implementation but that would leak then also into standardizing how we write resource paths in XML (see ```DomConfigurationWriter.toFilename(Resource)``` which only does a partial job at this - candidate for a refactoring I would say).

### CODE REVIEW

File: engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java [hunk 1]
```diff
@@ -559,8 +559,8 @@ private ReferenceDataCatalog createReferenceDataCatalog(ReferenceDataCatalogType
 
                         addVariablePath(name);
 
-                        String filenamePath = getStringVariable("filename", tfdt.getFilename());
-                        String filename = createFilename(filenamePath);
+                        final String filenamePath = getStringVariable("filename", tfdt.getFilename());
+                        final String filename = createFilename(filenamePath);
```
Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java]: Nooooooooooooooooooooooooooooooooooooooooooooooooooo NOT IN HERE! Then I'll need to merge when I do my commit. :scream: :sob: **whine**

File: engine/xml-config/src/test/resources/example-configuration-reference-data-resource-paths.xml [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+		<synonym-catalogs>
+
+			<text-file-synonym-catalog name="synonyms">
+				<filename>file://relative/path/to/synonyms.txt</filename>
+				<encoding>UTF8</encoding>
+				<case-sensitive>false</case-sensitive>
+			</text-file-synonym-catalog>
+		</synonym-catalogs>
+	</reference-data-catalog>
+
```
Comment (LosD) [inline engine/xml-config/src/test/resources/example-configuration-reference-data-resource-paths.xml]: Maybe add another one that isn't using `file://`just to make sure that those aren't screwed with (they probably aren't, but still).

**Comment by LosD** [comment]
While true that it is a "lazy" fix, LGTM, but see comment (only the last one :smile:)

Will you add the issue?

**Comment by kaspersorensen** [comment]
Created issue #1165 to refactor the way resources are externalized and read.

File: engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java (hunk 1 above)
Comment (ClaudiaPHI) [inline engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java]: sissi :-1:

Comment (ClaudiaPHI) [inline engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java]: I am mean  :-P :-D

Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java]: :D
