### PR TITLE
NPE when writing CSV file

### LINKED ISSUE #463: Weird stacktrace writing to CSV file
With DC4.0.4, observed the following stacktrace when writing a part of a file (using a filter) to a CSV file. The CSV file is fully written, all records are present, but just before completing the job, the following stack trace appears in the progress window:
```
java.lang.NullPointerException
 at org.datacleaner.extension.output.CreateCsvFileAnalyzer.getResultInternal(CreateCsvFileAnalyzer.java:197)
 at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:53)
 at org.datacleaner.extension.output.AbstractOutputWriterAnalyzer.getResult(AbstractOutputWriterAnalyzer.java:34)
 at org.datacleaner.job.tasks.CollectResultsTask.execute(CollectResultsTask.java:60)
 at org.datacleaner.job.concurrent.TaskRunnable.run(TaskRunnable.java:61)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
```

Worth a look, especially since the trace doesn't contain a lot of information as to what is wrong.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #463

### CODE REVIEW

**Comment by kaspersorensen** [comment]
oh darn, tabs instead of spaces ... lemme fix.

File: components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java [hunk 1]
```diff
@@ -160,15 +164,15 @@ public OutputWriter createOutputWriter() {
...
                 }
             }
         }
 
         if (columnToBeSortedOn != null) {
-            if (indexOfColumnToBeSortedOn == -1) {
-                this.isColumnToBeSortedOnPresentInInput = false;
-                indexOfColumnToBeSortedOn = columns.length;
+            if (_indexOfColumnToBeSortedOn == -1) {
+                this._isColumnToBeSortedOnPresentInInput = false;
```
Comment (tomaszguzialek) [inline components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java]: "this" is redundant when we have underscore in the name.
