### PR TITLE
Spark CSV write speed fixed by buffering and not needlessly checking isExists()

### LINKED ISSUE #902: Very poor write-performance of "Create CSV file" when executing in spark module
Although it "scales out" the performance of individual executor nodes is certainly wrong. We observed 6-8 records written per second. Strangely, it seems to write a lot faster when running via DC desktop (also to HDFS resource).

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #902

A few optimizations

 * Added buffering to the output stream (this did the trick)
 * Avoiding needless call to HdfsResource.isExists() - this might save some time because it happens again and again.
 * Avoiding re-reading the files on HDFS again and again by saving them as Strings in SparkJobContext instead. This means only the driver program needs to read them.

### CODE REVIEW

File: components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java [hunk 1]
```diff
@@ -142,7 +142,7 @@ public String getSuggestedLabel() {
 
     @Validate
     public void validate() {
-        if (file.isExists() && !overwriteFileIfExists) {
+        if (!overwriteFileIfExists && file.isExists()) {
```
Comment (LosD) [inline components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java]: A lot cheaper, I guess?

**Comment by LosD** [comment]
LGTM! Even saved quite a few lines of code

**Comment by LosD** [comment]
(Waiting for Travis)

**Comment by ClaudiaPHI** [comment]
LGTM!
