### PR TITLE
Bug/1470 removing linked component breaks job

### LINKED ISSUE #1339: Analyzer output stream columns are not always updated properly
When columns are removed from a job by deleting a transformer somewhere, then the input and output columns of analyzers (at least the dup detection analyzer is affected) are not properly updated, leading to inconsistent or incorrect job configurations.

Reproduction steps:
* Use the quick analysis wizard for duplicate detection to generate a dup detection for the Customers database.
* Add a CSV and an XLSX writer to the job, one writing the duplicates output stream, the other writing the uniques output stream.
* Remove the email transformer from the job
* Now open the duplicate detection analyzer set up. You will see the email (standardized) and domain (standardized) column are still there. That's incorrect.
* Remove the domain(standardized) columns then close the dup detection analyzer
* Open one of the writer components. You'll notice that the email (standardized) column is still there on both sides, but the domain (standardized) column is gone from the left-hand side. Also notice that all columns below the domain (standardized) have shifted place with one column. 

Expected behavior is that when I remove columns, they are removed throughout the entire following flow automatically, and that this happens without affecting the mapping of other columns.

### LINKED ISSUE #1470: Removing already linked component can break job
In some cases, when deleting a component whose output column has already been mapped to another column, then re-adding the same component again and mapping it to the same columns, _something_ gets confused.

### Steps to reproduce
1. Link an input column to a component
2. Link component to other component
3. Delete first component
4. Re-add component, and link it to the other component (using "Link to...") again.
5. Save and reload job.

### Expected outcome
Links fine, saves and reloads without issue

### Actual outcome
Either doesn't look like it is linked in the graph UI, or links the same column twice.
When opening job, it fails.

### Notes
The issue does not seem to be in "Link to...", but that the original component column links aren't deleted from the other component, which means the new component can/will be confused with the original. This makes it possibly related to #1339.

When the job is saved, it looks like the input column ids get a "2" attached, which is what breaks the loading. Part of the symptom might be from the fix to #1030 (I don't think that fix is wrong, though, it just exposes this issue).

We probably want to make sure that JaxbJobWriter refuses to save a job broken like this, instead of inventing ids for columns that doesn't exist.

### Workarounds
To avoid the issue, either delete the other component with the first, or make sure to manually remove the dangling references.

If you realize the job was broken when loading it, open it with an editor and look for input column ids that has a "2" attached in the end, without a corresponding output column, then remove the "2".

### PR DESCRIPTION
**Pull request by arjansh**
Fixes #1470.
Also fixes #1339.

When you remove a transformer or remove a field for a transformer's configuration, other components using fields provided by the transformer in an input column need to be updated in that such fields are removed, because they no longer are available.

This is achieved by registering a listener on a transformer when assigned such a field to a component. The listener removes such fields from components when they are removed from a transformer (or the transformer is removed).

### CODE REVIEW

**Comment by arjansh** [comment]
This pull request also fixes a large part of #1339. It fixes the part that deleting transformers is not propagated through the entire flow. It doesn't fix the part that mapping of other columns becomes corrupted.

**Comment by LosD** [comment]
Hmmm... Does it fix #1339 or does it only fix it partially? Your description makes it sound like a full fix, but the comment makes it sound partial :)

If only partial, you'll probably need to edit the description, otherwise it will close the issue when merged.

**Comment by arjansh** [comment]
It fixes #1339 completely. I updated my outdated comment.

**Comment by LosD** [comment]
That's totally what I wanted to hear. :-)

File: engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java [hunk 1]
```diff
@@ -322,11 +324,50 @@ public B setConfiguredProperty(String configuredName, Object value) {
     public B setConfiguredProperty(ConfiguredPropertyDescriptor configuredProperty, Object value) {
         final boolean changed = setConfiguredPropertyIfChanged(configuredProperty, value);
         if (changed) {
+            if (configuredProperty.isInputColumn()) {
+                for (TransformedInputColumn<?> transformedInputColumn : getTransformedInputColumns(value)) {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java]: Seems a little weird having non-functional for loop with a functional expression inside.

**Comment by jhorcicka** [comment]
Can anyone check and confirm/reject following?

Simple job with "customers", "concatenator", "text-case-transformer" and "value distribution": 
job-01
When I load and execute the job, everything goes fine. When I remove "concatenator", I get error as expected.
job-02
When I recreate the job to its original state: 
job-03
job-04
job-05
It can be executed again. But when I want to close the job I get the error again (I tried both saving and not-saving the job before closing it). 
job-06

File: engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java [hunk 2]
```diff
@@ -322,11 +324,50 @@ public B setConfiguredProperty(String configuredName, Object value) {
...
+                                            new ComponentBuilderTransformerChangeListener(this, configuredProperty)));
+                }
+            }
+
             onConfigurationChanged();
         }
         return (B) this;
     }
 
+    protected boolean isProvidingColumn(final TransformedInputColumn<?> transformedInputColumn,
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java]: Not sure if it makes sense, but if this was a method on TransformedInputColumn, you could use a method reference above.

File: engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java [hunk 3]
```diff
@@ -383,10 +424,62 @@ protected boolean setConfiguredPropertyIfChanged(final ConfiguredPropertyDescrip
...
+                                            dependentProperty.setValue(_configurableBean, null);
+                                        }
+                                    }
+                                }
+                            });
+        }
+    }
+
+    private static <E> E[] getArray(Class<E> clazz, List<?> baseList) {
+        E[] result = (E[]) Array.newInstance(clazz, baseList.size());
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java]: This seems expensive. Is it really needed?

Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java]: Oh, and "final" (goes for a lot of the new code in this file)  :)

File: engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+
+    public ComponentBuilderTransformerChangeListener(ComponentBuilder componentBuilder,
+            ConfiguredPropertyDescriptor propertyDescriptor) {
+        _componentBuilder = componentBuilder;
+        _propertyDescriptor = propertyDescriptor;
+    }
+
+    @Override
+    public void onAdd(TransformerComponentBuilder<?> builder) {
+        // Do nothing.
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java]: I've seen a lot of this in other implementations of TransformerChangeListener... Should we make an adapter at some point (not now)?

File: engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java [hunk 5]
```diff
@@ -334,7 +334,9 @@ protected void onRemovedInternal() {
      *            a new change listener
      */
     public void addChangeListener(TransformerChangeListener listener) {
-        _localChangeListeners.add(listener);
+        if (!_localChangeListeners.contains(listener)) {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java]: This scares me. I think we ping-ponged on `localChangeListeners.contains` in various places quite a few times. Maybe check if this was one of those places, and if it was, why it was removed. I'm afraid of re-opening new bugs.

File: engine/core/src/test/java/org/datacleaner/job/builder/BaseMockAnalyzer.java [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+    public void run(InputRow row, int distinctCount) {
+        // Do nothing.
+    }
+
+    @Override
+    public AnalyzerResult getResult() {
+        return null;
+    }
+
+}
```
Comment (LosD) [inline engine/core/src/test/java/org/datacleaner/job/builder/BaseMockAnalyzer.java]: Missing EOL

File: engine/core/src/test/java/org/datacleaner/job/builder/MockAnalyzer.java [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+    @MappedProperty("Columns")
+    public String[] _columnNames;
+
+    @Configured
+    public InputColumn<?> _column;
+
+    @Configured
+    @MappedProperty("Column")
+    public String _columnName;
+}
```
Comment (LosD) [inline engine/core/src/test/java/org/datacleaner/job/builder/MockAnalyzer.java]: Missing EOL

File: engine/core/src/test/java/org/datacleaner/job/builder/MultipleJobsAnalyzer.java [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+
+import org.datacleaner.api.ColumnProperty;
+import org.datacleaner.api.Configured;
+import org.datacleaner.api.InputColumn;
+
+public class MultipleJobsAnalyzer extends BaseMockAnalyzer {
+    @Configured
+    @ColumnProperty(escalateToMultipleJobs = true)
+    public InputColumn<?> _column;
+}
```
Comment (LosD) [inline engine/core/src/test/java/org/datacleaner/job/builder/MultipleJobsAnalyzer.java]: Missing EOL

File: engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+                            }
+                        }
+                    }
+                }
+            }
+        }
+    }
+
+    @Override
+    public boolean equals(Object object) {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java]: `hashcode()` seems to be missing (`equals()` and `hashcode()` should always be overridden in pairs).

You can use `Objects.hash(_componentBuilder, _propertyDescriptor)` for a quick implementation.

**Comment by LosD** [comment]
Mostly looks good to me, but check comments. Will do my own testing when I'm home.

**Comment by LosD** [comment]
BTW, anyone are more than welcome to test. We reaaaalllly don't want this to keep breaking.

File: engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java (hunk 3 above)
Comment (arjansh) [inline engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java]: I will add the final :), this method is really needed, because I have a list of objects and I need to pass a typed array to the ConfiguredPropertyDescriptor#setValue(Object, Object) method, or otherwise I'll get some exception that the value can't be set because it is of the wrong type. I could figure out no easier way to get a typed array from my list of objects (believe me, I tried).

File: engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java (hunk 4 above)
Comment (arjansh) [inline engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilderTransformerChangeListener.java]: Sounds reasonable. (not now however :))

File: engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java (hunk 5 above)
Comment (arjansh) [inline engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java]: I checked and I wasn't ping-ponged here. It is logical that it's scary, because it's a poor man's solution to the problem that the addChangeListener is in fact invoked way too often (as a result of this pull request) and this is the only way too ensure the number of listeners doesn't completely explode. With the current setup I could figure out no way to neatly remove listeners when they're no longer needed without going through a number of extremely complex setup hoops.

Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java]: That's good. And yeah, we need all that fixed.

**Comment by jhorcicka** [comment]
I re-tested the issue I posted (multiple times) and now it works fine.

**Comment by LosD** [comment]
LGTM!
