### PR TITLE
Fixes  #1313

### LINKED ISSUE #1313: Coalesce can't work with templates
The Coalesce units uses the name of datastores, so any kind of templating (including just changing the file name a datastore refers to) is broken.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes coalesce broken template

DONOTMERGE: There is one test failing. 

Can someone also take the branch for testing ? 

Fixes #1313

### CODE REVIEW

File: engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java [hunk 1]
```diff
@@ -915,9 +919,50 @@ private void applyProperties(final ComponentBuilder builder,
                     final Converter<?> customConverter = configuredProperty.createCustomConverter();
                     final Object value = stringConverter.deserialize(stringValue, configuredProperty.getType(),
                             customConverter);
+               
+                    if (name.equals(CoalesceMultipleFieldsTransformer.PROPERTY_UNITS)) {
```
Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: I guess this also needs to apply to `FuseStreamsComponent`

Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: If `FuseStreamsComponent` is using the same name it doesn't matter, but we may want to ensure that it is the correct type. We don't control the naming of all transformers.

File: engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java [hunk 2]
```diff
@@ -915,9 +919,50 @@ private void applyProperties(final ComponentBuilder builder,
...
+                        final CoalesceUnit[] units = (CoalesceUnit[]) value;
+
+                        final ArrayList<CoalesceUnit> newUnitsList = new ArrayList<CoalesceUnit>();
+                        final Set<Entry<String, InputColumn<?>>> mappingColumnsSet = mappingInputColumns.entrySet();
+                        for (int i = 0; i < units.length; i++) {
+                            final String[] oldInputColumnNames = units[i].getInputColumnNames();
+                            final ArrayList<InputColumn<?>> newInputColumns = new ArrayList<InputColumn<?>>();
+                            for (Entry<String, InputColumn<?>> entry : mappingColumnsSet) {
+                                final String column_id = entry.getKey();
+                                final String path = getPath(columnsTypes, column_id);
```
Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: Does this handle the case where the column isn't an input column, but the output from a transformer?

File: engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java [hunk 3]
```diff
@@ -915,9 +919,50 @@ private void applyProperties(final ComponentBuilder builder,
...
+                            //create new coalesce unit with the mapped columns. 
+                            if (!newInputColumns.isEmpty()) {
+                                final CoalesceUnit newCoalesceUnit = new CoalesceUnit(newInputColumns);
+                                newUnitsList.add(newCoalesceUnit);
+                            }
+                        }
 
+                        // If in the coalesce units we have inputcolumns names and not the physical names then we keep
+                        // the original value. Eg value="[&amp;#91;EQ name&amp;#44;NEQ name&amp;#93;]"/>
+                        if (!newUnitsList.isEmpty()) {
```
Comment (ClaudiaPHI) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: Here where it handle the case where is the output of a transformer

Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: :+1: (It might be a little easier to follow conversations is you instead reply directly to the original comment with something like "that's handled in line xxx", otherwise thing get very messy very fast if there are multiple threads of discussion).

**Comment by LosD** [comment]
Pretty resilient from changes to datastores (renames of files, templating), but found an issue when one column is an inputcolumn, and another is a transformed column.

File: engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java [hunk 4]
```diff
@@ -916,8 +919,68 @@ private void applyProperties(final ComponentBuilder builder,
                     final Object value = stringConverter.deserialize(stringValue, configuredProperty.getType(),
                             customConverter);
 
+                    
+                    if (configuredProperty.getBaseType().getName().equals(CoalesceUnit.class)) {
```
Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: Why not just use `value instanceof CoalesceUnit[]`?

**Comment by LosD** [comment]
Union still seems to fail

**Comment by LosD** [comment]
Hmmm... Might be an issue with what I'm try to do, though:

My job is using two columns in two tables from orderdb and unioning them. When I template them, I try to use four columns from a single table.

**Comment by LosD** [comment]
At least the UI doesn't support it. I'll try with another datastore that has multiple tables

**Comment by LosD** [comment]
Errrr... Something's off; I can't even open a simple fuse/coalesce job (just merging two colunms) as a template now.

**Comment by LosD** [comment]
Trying to rebuild, maybe something went wrong

**Comment by LosD** [comment]
Nope, same thing:
```
org.datacleaner.job.ComponentConfigurationException: Expected 0 output column(s), but found 1 (TransformerComponentBuilder[transformer=Fuse / Coalesce fields,inputColumns=[MetaModelInputColumn[PUBLIC.CUSTOMERS.CONTACTLASTNAME], MetaModelInputColumn[PUBLIC.CUSTOMERS.CONTACTFIRSTNAME]]])
Level:
    SEVERE
Stack Trace:
Expected 0 output column(s), but found 1 (TransformerComponentBuilder[transformer=Fuse / Coalesce fields,inputColumns=[MetaModelInputColumn[PUBLIC.CUSTOMERS.CONTACTLASTNAME], MetaModelInputColumn[PUBLIC.CUSTOMERS.CONTACTFIRSTNAME]]])
    org.datacleaner.job.JaxbJobReader.wireInputColumns(JaxbJobReader.java:647)
    org.datacleaner.job.JaxbJobReader.configureComponents(JaxbJobReader.java:486)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:460)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:402)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:339)
    org.datacleaner.windows.OpenAnalysisJobAsTemplateDialog$1.actionPerformed(OpenAnalysisJobAsTemplateDialog.java:119)
    javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    java.awt.Component.processMouseEvent(Unknown Source)
    javax.swing.JComponent.processMouseEvent(Unknown Source)
    java.awt.Component.processEvent(Unknown Source)
    java.awt.Container.processEvent(Unknown Source)
    java.awt.Component.dispatchEventImpl(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Window.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    java.awt.EventQueue.access$500(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)
Column 'datastores.customers.csv.family_name' not found. Available columns: [CONTACTLASTNAME, CONTACTFIRSTNAME]
    org.datacleaner.descriptors.ValidateMethodDescriptorImpl.convertThrownException(ValidateMethodDescriptorImpl.java:42)
    org.datacleaner.descriptors.AbstractMethodDescriptor.invoke(AbstractMethodDescriptor.java:83)
    org.datacleaner.descriptors.ValidateMethodDescriptorImpl.validate(ValidateMethodDescriptorImpl.java:37)
    org.datacleaner.lifecycle.LifeCycleHelper.validate(LifeCycleHelper.java:160)
    org.datacleaner.job.builder.AbstractComponentBuilder.isConfigured(AbstractComponentBuilder.java:250)
    org.datacleaner.job.JaxbJobReader.wireInputColumns(JaxbJobReader.java:645)
    org.datacleaner.job.JaxbJobReader.configureComponents(JaxbJobReader.java:486)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:460)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:402)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:339)
    org.datacleaner.windows.OpenAnalysisJobAsTemplateDialog$1.actionPerformed(OpenAnalysisJobAsTemplateDialog.java:119)
    javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    java.awt.Component.processMouseEvent(Unknown Source)
    javax.swing.JComponent.processMouseEvent(Unknown Source)
    java.awt.Component.processEvent(Unknown Source)
    java.awt.Container.processEvent(Unknown Source)
    java.awt.Component.dispatchEventImpl(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Window.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    java.awt.EventQueue.access$500(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)
Column 'datastores.customers.csv.family_name' not found. Available columns: [CONTACTLASTNAME, CONTACTFIRSTNAME]
    org.datacleaner.components.fuse.CoalesceUnit.updateInputColumns(CoalesceUnit.java:145)
    org.datacleaner.components.fuse.CoalesceMultipleFieldsTransformer.validate(CoalesceMultipleFieldsTransformer.java:88)
    sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    java.lang.reflect.Method.invoke(Unknown Source)
    org.datacleaner.descriptors.AbstractMethodDescriptor.invoke(AbstractMethodDescriptor.java:79)
    org.datacleaner.descriptors.ValidateMethodDescriptorImpl.validate(ValidateMethodDescriptorImpl.java:37)
    org.datacleaner.lifecycle.LifeCycleHelper.validate(LifeCycleHelper.java:160)
    org.datacleaner.job.builder.AbstractComponentBuilder.isConfigured(AbstractComponentBuilder.java:250)
    org.datacleaner.job.JaxbJobReader.wireInputColumns(JaxbJobReader.java:645)
    org.datacleaner.job.JaxbJobReader.configureComponents(JaxbJobReader.java:486)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:460)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:402)
    org.datacleaner.job.JaxbJobReader.create(JaxbJobReader.java:339)
    org.datacleaner.windows.OpenAnalysisJobAsTemplateDialog$1.actionPerformed(OpenAnalysisJobAsTemplateDialog.java:119)
    javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    java.awt.Component.processMouseEvent(Unknown Source)
    javax.swing.JComponent.processMouseEvent(Unknown Source)
    java.awt.Component.processEvent(Unknown Source)
    java.awt.Container.processEvent(Unknown Source)
    java.awt.Component.dispatchEventImpl(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Window.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    java.awt.EventQueue.access$500(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by LosD** [comment]
LGTM and Travis is happy. Merging!
