### PR TITLE
#1222 - HDFS resource (with template) loading on Spark

### LINKED ISSUE #1222: Spark job fails when CSV datastore defines templated server definition
I'm running a spark job where my conf.xml defines a CSV datastore that defines a filename using the `{org.datacleaner.hadoop.environment}` template server. Somehow this still does not seem to work:
```
6/03/10 08:30:01 ERROR ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: Illegal character in authority at index 7: hdfs://{org.datacleaner.hadoop.environment}/datacleaner/data/companies_i18n.csv
java.lang.IllegalArgumentException: Illegal character in authority at index 7: hdfs://{org.datacleaner.hadoop.environment}/datacleaner/data/companies_i18n.csv
	at java.net.URI.create(URI.java:852)
	at org.datacleaner.spark.SparkConfigurationReaderInterceptor.createResource(SparkConfigurationReaderInterceptor.java:62)
	at org.datacleaner.configuration.JaxbConfigurationReader.createDatastore(JaxbConfigurationReader.java:1251)
	at org.datacleaner.configuration.JaxbConfigurationReader.createDatastoreCatalog(JaxbConfigurationReader.java:690)
	at org.datacleaner.configuration.JaxbConfigurationReader.create(JaxbConfigurationReader.java:286)
	at org.datacleaner.configuration.JaxbConfigurationReader.create(JaxbConfigurationReader.java:206)
	at org.datacleaner.configuration.JaxbConfigurationReader.read(JaxbConfigurationReader.java:177)
	at org.datacleaner.spark.SparkJobContext.getConfiguration(SparkJobContext.java:124)
	at org.datacleaner.spark.SparkJobContext.getAnalysisJobBuilder(SparkJobContext.java:151)
	at org.datacleaner.spark.SparkJobContext.getAnalysisJob(SparkJobContext.java:143)
	at org.datacleaner.spark.SparkAnalysisRunner.run(SparkAnalysisRunner.java:87)
	at org.datacleaner.spark.Main.main(Main.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:525)
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: hdfs://{org.datacleaner.hadoop.environment}/datacleaner/data/companies_i18n.csv
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
```

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #1222 

This is a bit of a dirty workaround since it just strips out any Hadoop-resource server definition from HDFS urls on Spark. I couldn't imagine another way to do it that wasn't more or less a complete rewrite of how resources are loaded. The (pretty significant) drawback of this approach is that now you cannot refer to a HDFS resource outside of the cluster that spark is running in. I guess that could be a future use case if someone has multiple Hadoop clusters (for some reason) that need to process data across in the same job?

For the reviewer: Please double check the regex Pattern that I've used. I think it's fine, but please give a second opinion.

### CODE REVIEW

File: engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java [hunk 1]
```diff
@@ -45,6 +47,9 @@
     private static final DescriptorProvider DESCRIPTOR_PROVIDER = new ClasspathScanDescriptorProvider(TASK_RUNNER)
             .scanPackage("org.datacleaner", true).scanPackage("com.hi", true).scanPackage("com.neopost", true);
     private static final StorageProvider STORAGE_PROVIDER = new InMemoryStorageProvider(500, 20);
+    
+    // used to strip e.g. {org.datacleaner.hadoop.environment} out of HDFS URIs
+    private static final Pattern STRIP_SERVER_PATTERN = Pattern.compile("(.+)://\\{.+\\}/(.+)");
```
Comment (LosD) [inline engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java]: Reuse pattern you made final above (in HadoopResourceBuilder) :)

**Comment by LosD** [comment]
LGTM, except an existing regex pattern could be reused

**Comment by LosD** [comment]
We currently have a problem with the Spark runner, in that the uploaded conf.xml needs to be stripped. for unrelated datasources. If this PR was expanded with a bit of resilience against i.e. "C:\sdfgfd\dfdf\dfdfdf.csv" resources, that may not be necessary.

It is partially unrelated, though, so a new issue and PR would maybe make more sense.

Your call :)

**Comment by kaspersorensen** [comment]
I don't think that would solve the issue you're talking about. It would be better to produce a conf.xml file without those datastores in the first place.

**Comment by LosD** [comment]
You're probably right
