### PR TITLE
Bug/742 execute without analyzers error

### LINKED ISSUE #742: "Execute without Analyzers" window exception
Scenario: 

1. Start a job with orderDB as datastore 
2. Add on canvas Customers and Employees table 
3. Add a "Union " and select all column 
4. Press Execute button 
5. "Execute without analyzers" window appears. 

<b> Exception 1 </b>
6.  Select "Write to CSV" 
 The following exception occurs: 

```

Unexpected error!
 

Message:
    java.lang.IllegalArgumentException: Invalid value type: java.io.File, expected: org.apache.metamodel.util.Resource
Level:
    SEVERE
Stack Trace:
Invalid value type: java.io.File, expected: org.apache.metamodel.util.Resource
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredPropertyIfChanged(AbstractComponentBuilder.java:350)
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredProperty(AbstractComponentBuilder.java:292)
    org.datacleaner.job.builder.AnalyzerComponentBuilder.setConfiguredProperty(AnalyzerComponentBuilder.java:326)
    org.datacleaner.job.builder.AnalyzerComponentBuilder.setConfiguredProperty(AnalyzerComponentBuilder.java:58)
    org.datacleaner.job.builder.AbstractComponentBuilder.setConfiguredProperty(AbstractComponentBuilder.java:287)
    org.datacleaner.panels.ExecuteJobWithoutAnalyzersDialog$2.actionPerformed(ExecuteJobWithoutAnalyzersDialog.java:150)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
```
screen shot 2015-10-07 at 2 12 32 pm

```

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #742  

Fixed the writing to a file.

### CODE REVIEW

File: desktop/ui/src/main/java/org/datacleaner/panels/ExecuteJobWithoutAnalyzersDialog.java [hunk 1]
```diff
@@ -180,11 +188,11 @@ private File createFile(String filenamePrefix, String extension) {
                 filename = filenamePrefix + "_" + attempt + extension;
             }
 
-            File candidate = new File(directory, filename);
-            if (!candidate.exists()) {
-                return candidate;
+            final File file = new File(directory, filename);
+            FileResource resourceCandidate = new FileResource(file);
```
Comment (kaspersorensen) [inline desktop/ui/src/main/java/org/datacleaner/panels/ExecuteJobWithoutAnalyzersDialog.java]: final :)

File: desktop/ui/src/main/java/org/datacleaner/panels/ExecuteJobWithoutAnalyzersDialog.java [hunk 2]
```diff
@@ -143,12 +144,19 @@ public void actionPerformed(ActionEvent e) {
...
+
                 analyzer.addInputColumns(copyAnalysisJobBuilder.getAvailableInputColumns(Object.class));
 
                 final String formattedDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
 
-                analyzer.setConfiguredProperty("File",
-                        createFile("datacleaner-" + formattedDate + "-output", filenameExtension));
+                final FileResource resource = createResource("datacleaner-" + formattedDate + "-output",
+                        filenameExtension);
+                if (filenameExtension.equals(".xls") || filenameExtension.equals(".xlsx")) {
```
Comment (kaspersorensen) [inline desktop/ui/src/main/java/org/datacleaner/panels/ExecuteJobWithoutAnalyzersDialog.java]: This is quite unclear why the "if" is here. I imagine it's because the CreateExcelAnalyzer is still using a java.io.File? If so then construct the if around that fact so that it's clear:

if (analyzer.getComponentClass() == CreateExcelAnalyzer.class) { ...

Comment (ClaudiaPHI) [inline desktop/ui/src/main/java/org/datacleaner/panels/ExecuteJobWithoutAnalyzersDialog.java]: ok better solution

**Comment by kaspersorensen** [comment]
LGTM!
