### PR TITLE
bug/1423 ValueDistributionAnalyzer, unconfigured output, execution enabled

### LINKED ISSUE #1423: NullCheckFilter: out of bounds exception
In a simple job with "orderdb", "null check filter" and "value distribution" I get "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0". 

null-filter-oobe

### PR DESCRIPTION
**Pull request by jhorcicka**
Fixes #1423  

Original reason for this fix was an exception while running job with unconfigured input columns in ValueDistributionAnalyzer. The fix is general, though. Every exception in AnalysisJobBuilderWindowImpl.updateStatusLabel() makes the job un-executable now.

### CODE REVIEW

File: desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java [hunk 1]
```diff
@@ -505,10 +512,10 @@ public void updateStatusLabel() {
                     setStatusLabelWarning();
                 }
             } catch (Exception ex) {
+                executeable = false;
```
Comment (jhorcicka) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: This setting to false was in "if" and "else if" branches but not in the "else" branch. I looked into GIT history and it has never been there. But @LosD said that job execution was probably blocked in the past. It means it was achieved in a different way which I don't know. 

And secondly, is there any reason why this last "else" branch did not set "executable" to false? Or is that just something that was forgotten?

Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: I think it was, but I can't really back it up. Maybe try using an older version (4.5.x or something) and see if I'm right, and if I was, see what has changed.

That executable flag almost _must_ be on purpose. Otherwise why would it be there at all? But I'm not sure why.

Comment (LosD) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: Ah, too early in the morning. Didn't notice it was also being used for other purposes. But it still partially holds: If all branches are supposed to set the executable flag to false, why do in inside the if construct at all?

**Comment by ClaudiaPHI** [comment]
I belive we can fix this instead in ValueDistributionAnalyzer, with a validate method. 

````
    @Validate
    public void validate() {
      if () {
throw new IllegalStateException("No input Column select")
}

}

**Comment by LosD** [comment]
@ClaudiaPHI The issue is that validation _does_ trigger, but the job is still executable.

File: desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java (hunk 1 above)
Comment (jhorcicka) [inline desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java]: I tried it in 4.0.11 and in 4.5 and without any configured column in ValueDistributionAnalyzer the job can still be executed. However, there is no error/exception mentioned (just nothing happens / no rows processed).

**Comment by LosD** [comment]
Still not a fan of the executable flag, but that's not anything now, so not really a required fix for this PR. Otherwise LGTM.

There's merge issues, though.

**Comment by jhorcicka** [comment]
Updated from master.

**Comment by arjansh** [comment]
LGTM!
