### PR TITLE
Issue #370: Improved exception hierarchy+handling in validation cases.

### LINKED ISSUE #370: Inconsistency in @validate and automagic checks in Execute button
The execute button in DataCleaner disables when a job fails the automagic checks (eg no columns selected), but when a transformer or anylyzer does any custom checking using the @validate annotation and rejects the job, the execute button remains active. Hitting the execute button results in an exception being thrown.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #370

### CODE REVIEW

File: engine/core/src/main/java/org/datacleaner/descriptors/AbstractMethodDescriptor.java [hunk 1]
```diff
@@ -70,22 +74,29 @@ public final String toString() {
         return getClass().getSimpleName() + "[method=" + _name + "]";
     }
 
-    protected final void invoke(Object component) {
+    protected final void invoke(Object component) throws RuntimeException, IllegalStateException {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/descriptors/AbstractMethodDescriptor.java]: Aren't these redundant?

File: engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java [hunk 2]
```diff
@@ -774,9 +785,11 @@ public AnalysisJobMetadata createMetadata() {
      * 
      * @return
      * @throws IllegalStateException
-     *             if the job is invalidly configured.
+     *             if the job is invalidly configured. See
+     *             {@link #isConfigured(boolean)} for detailed exception
+     *             descriptions.
      */
-    public AnalysisJob toAnalysisJob() throws IllegalStateException {
+    public AnalysisJob toAnalysisJob() throws RuntimeException {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java]: Same here. The @throws is enough for documentation purposes.

**Comment by LosD** [comment]
It seems like a bit more than fixing #370, as it also seems to fix the issue with transformers that produces results not allowing executing the job, but I guess they're somehow related anyway.

I'm not too fond of using the throws keyword for RuntimeExceptions, but other than that it looks good.

File: engine/core/src/main/java/org/datacleaner/descriptors/AbstractMethodDescriptor.java (hunk 1 above)
Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/descriptors/AbstractMethodDescriptor.java]: Well yes and no :) The RuntimeException is basically thrown if anything goes wrong in the validation method itself. The IllegalStateException is explicitly mentioned also because the code here (the "wrapper" around the validation method) might also throw such an exception.

File: engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java (hunk 2 above)
Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java]: The doc needs an update yes. But do you think there's anything wrong with both having it in javadoc and as a method modifier? IMO that is best practice?

Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java]: Hmmmm, as far as I remember best practice is more or less only to have RuntimeExceptions in ```@throws```. At least it seems to be the way their own code is used, and I think best practice would be not to having people guessing if it is a checked exception or not (of course that matters a little less now, with the IDE checking it live).

Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java]: Hmm I always learned that putting the exceptions there was nice as a way of documenting it to the next guy who reads the code. Of course there are never any guarantees that an unchecked exception cannot be thrown, but if you explicitly put it on the throws-list, then you tell the consumer of the code that it is not uncommon or that there are specific scenarios where it might fail.
