### PR TITLE
Long(er) chains of output data streams

### LINKED ISSUE #583: Jobs with multiple OutputDataStream chained together
Right now we support a single OutputDataStream, but when adding more somehow we run into situations where AnalysisListener.componentBegin is called thousands of times and typically also the components are wrongly configured. Somewhere there must be a recursion gone wrong or something :-)

Can be reproduced simply by adding 3 Completeness analyzers to a job. Chain them all together by using e.g. the "Incomplete rows" stream. It works with 2 Completeness analyzers (1 output data stream) but breaks at 3+.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #583 by introducing an identifyable "RowProcessingStream" to hold Table and AnalysisJob

### CODE REVIEW

File: engine/core/src/main/java/org/datacleaner/job/runner/ConsumeRowHandler.java [hunk 1]
```diff
@@ -174,11 +174,14 @@ public ConsumeRowResult consumeRow(final InputRow row) {
 
         final RowProcessingPublisher publisher;
         if (rowConsumeConfiguration.table != null) {
-            publisher = rowProcessingPublishers.getRowProcessingPublisher(rowConsumeConfiguration.table);
-            if (publisher == null) {
+            @SuppressWarnings("deprecation")
+            RowProcessingPublisher tablePublisher = rowProcessingPublishers
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/runner/ConsumeRowHandler.java]: final missing. But why introduce the temp variable at all? Original seemed clearer.

File: engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublishers.java [hunk 2]
```diff
@@ -134,13 +141,30 @@ private void registerOutputDataStream(final RowProcessingPublisher parentPublish
         return physicalColumnsArray;
     }
 
+    @Deprecated
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublishers.java]: JavaDoc with a deprecation reason here would be nice

File: engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingStream.java [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+        return _table;
+    }
+
+    @Override
+    public int hashCode() {
+        final int prime = 31;
+        int result = 1;
+        result = prime * result + ((_analysisJob == null) ? 0 : _analysisJob.hashCode());
+        result = prime * result + ((_table == null) ? 0 : _table.hashCode());
+        return result;
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingStream.java]: Objects.hash(...)?

File: engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingStream.java [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+                return false;
+        } else if (!_analysisJob.equals(other._analysisJob))
+            return false;
+        if (_table == null) {
+            if (other._table != null)
+                return false;
+        } else if (!_table.equals(other._table))
+            return false;
+        return true;
+    }
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingStream.java]: Something like:
```
if (this == object) {
    return true;
} else if (obj == null || !(obj instanceof RowProcessingStream)) {
    return false;
} else {
    return Objects.equals(_analysisJob, other._analysisJob && Objects.equals(_table, other._table)
}
```
Seems quite a bit more readable to me.

File: engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java [hunk 5]
```diff
@@ -88,7 +93,10 @@ public void onComplete(Task task) {
 
     @Override
     public void onError(Task task, Throwable throwable) {
-        _success.set(false);
+        boolean alreadyRegisteredError = _errorsReported.getAndSet(true);
+        if (!alreadyRegisteredError) {
```
Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java]: Why introduce a variable here?

**Comment by LosD** [comment]
Looks good, besides minor stuff.

File: engine/core/src/main/java/org/datacleaner/job/runner/ConsumeRowHandler.java (hunk 1 above)
Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/job/runner/ConsumeRowHandler.java]: Right. The temp variable is needed for the ```@SuppressWarnings``` annotation :S

File: engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java (hunk 5 above)
Comment (kaspersorensen) [inline engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java]: Mostly because I find the meaning of the return of .getAndSet a little bit hard to infer. So naming it makes it clearer to read the if sentence: "if not already registered error".
