### PR TITLE
Bug/356 uppercase extensions

### LINKED ISSUE #356: Dragging CSV file onto drop zone leads to NullPointerException
When I drag any of two attached CSV files on the DropZone in DC4  pro edition, I'll get a NullPointerException.

This happens if the CSV is not yet known as a datastore in DataCleaner. Once it is added, it work OK.

The CSV files seem to be nothing special, but find them attached anyway.

### PR DESCRIPTION
**Pull request by tomaszguzialek**
Fixes #356

Also showing an "Unrecognized file type" pop-up when an unsupported file is chosen in the file dialog (it caused an NPE; dropping does not react at all for unknown files). An unsupported file is for example a JPG or no extension at all (despite being a properly formatted CSV file wrt the contents).

### CODE REVIEW

File: desktop/ui/src/main/java/org/datacleaner/util/DatastoreCreationUtil.java [hunk 1]
```diff
@@ -57,7 +57,7 @@ protected static FileDatastoreEnum getDatastoreTypeFromFile(File file) {
             final String extension = FilenameUtils.getExtension(file.getName());
 
             for (FileDatastoreEnum datastoreType : EnumSet.allOf(FileDatastoreEnum.class)) {
-                if (datastoreType._extensions.contains(extension)) {
+                if (datastoreType._extensions.contains(extension.toLowerCase())) {
```
Comment (kaspersorensen) [inline desktop/ui/src/main/java/org/datacleaner/util/DatastoreCreationUtil.java]: Are there any risks that "extension" variable is null? I could imagine that FilenameUtils would return null if the filename does not have any dot in it.

Comment (tomaszguzialek) [inline desktop/ui/src/main/java/org/datacleaner/util/DatastoreCreationUtil.java]: FilenameUtils.getExtension() returns an empty string instead of a null.

**Comment by kaspersorensen** [comment]
Ok, looks good to me then.
