### PR TITLE
Monitor reference data dialogs

### LINKED ISSUE #1352: Enable configuration of reference data in the monitor
The monitor has no way of working with the reference data, making it necessary to upload a new configuration file. This is a pretty error-prone process, both because of the ease and tough consequences of corrupting the file, but also simply because there's a good chance the user will be juggling several configuration files, making it easy to use the wrong one.

### PR DESCRIPTION
**Pull request by jhorcicka**
Resolves #1352 

Support for reference data in Monitor. Wizards for creating dictionaries (simple, text-file, datastore), synonym catalogs (text-file, datastore) and string patterns (simple, datastore, regex-swap). 

file-dictionary
reference-data
new-string-pattern

### CODE REVIEW

**Comment by LosD** [comment]
I'm getting a 500 when trying to upload synonym file

**Comment by jhorcicka** [comment]
Can you provide details? It works in my case.

**Comment by LosD** [comment]
I'm on it

**Comment by LosD** [comment]
```
 com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.Set org.datacleaner.monitor.referencedata.ReferenceDataService.getStringPatterns(org.datacleaner.monitor.shared.model.TenantIdentifier)' threw an unexpected exception: java.lang.IllegalStateException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.datacleaner.monitor.server.GwtCacheControlFilter.doFilter(GwtCacheControlFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]
	at org.datacleaner.configuration.JaxbConfigurationReader.unmarshall(JaxbConfigurationReader.java:214)
	at org.datacleaner.configuration.JaxbConfigurationReader.create(JaxbConfigurationReader.java:196)
	at org.datacleaner.configuration.JaxbConfigurationReader.read(JaxbConfigurationReader.java:168)
	at org.datacleaner.monitor.configuration.ConfigurationCache$1.eval(ConfigurationCache.java:136)
	at org.datacleaner.monitor.configuration.ConfigurationCache$1.eval(ConfigurationCache.java:133)
	at org.datacleaner.repository.file.FileRepositoryFile.readFile(FileRepositoryFile.java:149)
	at org.datacleaner.monitor.configuration.ConfigurationCache.readConfiguration(ConfigurationCache.java:133)
	at org.datacleaner.monitor.configuration.ConfigurationCache.readConfiguration(ConfigurationCache.java:110)
	at org.datacleaner.monitor.configuration.ConfigurationCache.getAnalyzerBeansConfiguration(ConfigurationCache.java:95)
	at org.datacleaner.monitor.configuration.TenantContextImpl.getConfiguration(TenantContextImpl.java:149)
	at org.datacleaner.monitor.server.ReferenceDataServiceImpl.getReferenceDataCatalog(ReferenceDataServiceImpl.java:81)
	at org.datacleaner.monitor.server.ReferenceDataServiceImpl.getStringPatterns(ReferenceDataServiceImpl.java:57)
	at org.datacleaner.monitor.server.ReferenceDataServiceServlet.getStringPatterns(ReferenceDataServiceServlet.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 67 more
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
	at org.datacleaner.configuration.JaxbConfigurationReader.unmarshall(JaxbConfigurationReader.java:212)
	... 84 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	... 88 more

```

**Comment by LosD** [comment]
After it fails, I keep getting the same exception whenever reloading the page.

I tried to to upload a synonym file, btw: https://gist.github.com/LosD/143a0fba44570d0fe7937cd085fdab9c

**Comment by LosD** [comment]
The exception is no wonder; It nuked the conf.xml file completely

**Comment by jhorcicka** [comment]
I don't think it's a synonym-file problem. According to the message it's string-pattern related. Did you create any "complex" string-pattern before the file-synonym file upload? Your conf.xml is now broken, you'll keep getting the error until it is fixed.

**Comment by LosD** [comment]
I did nothing else that upload the synonym file as the very first thing.

**Comment by jhorcicka** [comment]
Which is not good and we should somehow do a configuration-file-consistency-check after the content has been changed.

**Comment by arjansh** [comment]
Uploading a synonyms catalog works for me.

**Comment by LosD** [comment]
But there's apparently no way to choose?

**Comment by LosD** [comment]
D'oh! It's the wrong branch I'm testing

**Comment by jhorcicka** [comment]
Perhaps you are testing the first one, right? :-)

**Comment by LosD** [comment]
Yep!

**Comment by LosD** [comment]
Comments from sprint review:
- "Reference Data" should be "Reference data" (uncapitalized 'd')
- The entry field for simple dictionary is too small (should at least fill dialog width to the right).
- Descriptions should be a bit better

**Comment by arjansh** [comment]
When registering a Regex swap string pattern, the wizard indicates it consists of three steps. When I go to the second step, where I select a Category, I can't go back to the first step and after selecting the category and clicking the Next button, I go to the step where I select the Regex name, but the indicator stays at the '2' of the second step. After selecting a Regex name and clicking next, it says the reference data was created, but the indicator is still at '2'. I don't know if it is necessary to make the Previous button work, but it would be nice if the indicator would move along nicely.

**Comment by arjansh** [comment]
I get a stacktrace in tomcat and an unresponsive user interface when I register a dictionary with a name that already is used:

```
15:50:20.049 [http-apr-8080-exec-5] INFO  o.d.m.c.ConfigurationCache - Reading configuration from file: /demo/conf.xml
15:50:20.067 [http-apr-8080-exec-5] WARN  o.d.monitor.server.SecureGwtServlet - Unexpected exception occurred in GWT servlet: com.google.gwt.user.server.rpc.Une
xpectedException
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.Set org.datacleaner.monitor.referencedata.ReferenceDataService.get
StringPatterns(org.datacleaner.monitor.shared.model.TenantIdentifier)' threw an unexpected exception: java.lang.IllegalStateException: Dictionary name is not un
ique: file_dict.txt
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415) ~[gwt-servlet-2.7.0.jar:na]
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605) ~[gwt-servlet-2.7.0.jar:na]
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333) ~[gwt-servlet-2.7.0.jar:na]
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303) ~[gwt-servlet-2.7.0.jar:na]
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373) ~[gwt-servlet-2.7.0.jar:na]
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62) ~[gwt-servlet-2.7.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [servlet-api.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.36]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205) [rewrite-servlet-2.0.12.Final.jar:2.0.12.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.36]
        at org.datacleaner.monitor.server.GwtCacheControlFilter.doFilter(GwtCacheControlFilter.java:70) [DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.36]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.9.REL
EASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.9.RE
LEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.9.RELEASE.j
ar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [spring-security-web-3.2.9.RELEASE.jar:3.
2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [spring-security-web-3
.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146) [spring-s
ecurity-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [sprin
g-security-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [spring-security-web-3.2.9.RELEASE.ja
r:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) [spring-security-web-3.2.9
.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) [spr
ing-security-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) [spring-security-web-3.2.9.RELEASE.jar:3.2.9.RELE
ASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [s
pring-security-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.2
.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.9.RELEASE.jar:3.2.9
.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) [spring-web-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) [spring-web-4.1.9.RELEASE.jar:4.1.9.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.36]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.36]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099) [tomcat-coyote.jar:8.0.36]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670) [tomcat-coyote.jar:8.0.36]
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2508) [tomcat-coyote.jar:8.0.36]
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2497) [tomcat-coyote.jar:8.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.36]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.lang.IllegalStateException: Dictionary name is not unique: file_dict.txt
        at org.datacleaner.configuration.JaxbConfigurationReader.checkName(JaxbConfigurationReader.java:1465) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.configuration.JaxbConfigurationReader.createReferenceDataCatalog(JaxbConfigurationReader.java:518) ~[DataCleaner-xml-config-5.1.3-SNA
PSHOT.jar:na]
        at org.datacleaner.configuration.JaxbConfigurationReader.create(JaxbConfigurationReader.java:290) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.configuration.JaxbConfigurationReader.create(JaxbConfigurationReader.java:200) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.configuration.JaxbConfigurationReader.read(JaxbConfigurationReader.java:171) ~[DataCleaner-xml-config-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.configuration.ConfigurationCache$1.eval(ConfigurationCache.java:136) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.configuration.ConfigurationCache$1.eval(ConfigurationCache.java:133) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.repository.file.FileRepositoryFile.readFile(FileRepositoryFile.java:149) ~[DataCleaner-engine-core-5.1.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.configuration.ConfigurationCache.readConfiguration(ConfigurationCache.java:133) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT
.jar:na]
        at org.datacleaner.monitor.configuration.ConfigurationCache.readConfiguration(ConfigurationCache.java:110) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT
.jar:na]
        at org.datacleaner.monitor.configuration.ConfigurationCache.getAnalyzerBeansConfiguration(ConfigurationCache.java:95) ~[DataCleaner-monitor-services-5.1
.3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.configuration.TenantContextImpl.getConfiguration(TenantContextImpl.java:149) ~[DataCleaner-monitor-services-5.1.3-SNAPSHOT.ja
r:na]
        at org.datacleaner.monitor.server.ReferenceDataServiceImpl.getReferenceDataCatalog(ReferenceDataServiceImpl.java:91) ~[DataCleaner-monitor-services-5.1.
3-SNAPSHOT.jar:na]
        at org.datacleaner.monitor.server.ReferenceDataServiceImpl.getStringPatterns(ReferenceDataServiceImpl.java:59) ~[DataCleaner-monitor-services-5.1.3-SNAP
SHOT.jar:na]
        at org.datacleaner.monitor.server.ReferenceDataServiceServlet.getStringPatterns(ReferenceDataServiceServlet.java:74) ~[DataCleaner-monitor-services-5.1.
3-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587) ~[gwt-servlet-2.7.0.jar:na]
        ... 66 common frames omitted
```

File: engine/core/src/test/java/org/datacleaner/reference/regexswap/RegexSwapClientTest.java [hunk 1]
```diff
@@ -32,6 +27,8 @@
 import org.junit.Assume;
 import org.junit.Test;
 
+import static org.junit.Assert.*;
```
Comment (arjansh) [inline engine/core/src/test/java/org/datacleaner/reference/regexswap/RegexSwapClientTest.java]: Why remove the four specific imports from above and replace them with a generic import?

File: engine/core/src/test/java/org/datacleaner/reference/regexswap/RegexSwapClientTest.java [hunk 2]
```diff
@@ -72,4 +69,4 @@ public void testUpdateContent() throws Exception {
             assertTrue(client.getRegexes(category).contains(regex));
         }
     }
-}
+}
```
Comment (arjansh) [inline engine/core/src/test/java/org/datacleaner/reference/regexswap/RegexSwapClientTest.java]: Newline at end of file has been removed.

**Comment by jhorcicka** [comment]
@LosD 
* "Reference **d**ata" item in menu. 
* Text entry fields are now 100% width. 
* Descriptions were added at particular wizard-pages. 

@arjansh 
* Regex swap wizard page indexes were fixed. 
* Unique name checking was added.

File: monitor/extensions/referencedata-wizards/src/test/resources/example_repo/demo/conf.xml [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+		</synonym-catalogs>
+	</reference-data-catalog>
+
+	<custom-taskrunner
+			class-name="org.datacleaner.monitor.configuration.SharedTaskRunner" />
+
+	<custom-descriptor-provider
+			class-name="org.datacleaner.monitor.configuration.SharedDescriptorProvider" />
+
+</configuration>
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/test/resources/example_repo/demo/conf.xml]: Missing EOL

File: monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/file/FileSynonymCatalogReferenceDataWizardTest.java [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+        FileSynonymCatalogReferenceDataWizard wizard = new FileSynonymCatalogReferenceDataWizard();
+        assertNotEquals("", wizard.getDisplayName());
+    }
+
+    @Test
+    public void testGetExpectedPageCount() throws Exception {
+        FileSynonymCatalogReferenceDataWizard wizard = new FileSynonymCatalogReferenceDataWizard();
+        assertEquals(1, wizard.getExpectedPageCount());
+    }
+}
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/file/FileSynonymCatalogReferenceDataWizardTest.java]: Missing EOL

File: monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/file/FileSynonymCatalogReferenceDataPageTest.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+import static org.junit.Assert.assertNotEquals;
+
+public class FileSynonymCatalogReferenceDataPageTest {
+
+    @Test
+    public void testGetNameLabel() throws Exception {
+        FileSynonymCatalogReferenceDataPage page = new FileSynonymCatalogReferenceDataPage(null);
+        assertNotEquals("", page.getNameLabel());
+    }
+}
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/file/FileSynonymCatalogReferenceDataPageTest.java]: Missing EOL

File: monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/datastore/DatastoreSynonymCatalogReferenceDataWizardTest.java [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+        DatastoreSynonymCatalogReferenceDataWizard wizard = new DatastoreSynonymCatalogReferenceDataWizard();
+        assertNotEquals("", wizard.getDisplayName());
+    }
+
+    @Test
+    public void testGetExpectedPageCount() throws Exception {
+        DatastoreSynonymCatalogReferenceDataWizard wizard = new DatastoreSynonymCatalogReferenceDataWizard();
+        assertEquals(5, wizard.getExpectedPageCount());
+    }
+}
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/datastore/DatastoreSynonymCatalogReferenceDataWizardTest.java]: Missing EOL

File: monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/datastore/DatastoreSynonymCatalogReferenceDataWizardSessionTest.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+    @Test
+    public void testNextSynonymColumn() throws Exception {
+        DatastoreSynonymCatalogReferenceDataWizardSession session =
+                new DatastoreSynonymCatalogReferenceDataWizardSession(TestHelper.getReferenceDataWizardContextMock());
+        assertNull(session.getAddNextSynonymColumn());
+        session.setAddNextSynonymColumn("on");
+        assertEquals("on", session.getAddNextSynonymColumn());
+    }
+}
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/test/java/org/datacleaner/monitor/server/wizard/synonymcatalog/datastore/DatastoreSynonymCatalogReferenceDataWizardSessionTest.java]: Missing EOL

**Comment by LosD** [comment]
Okay, I got tired of repeating... All new files seems to miss the final EOL :)

**Comment by LosD** [comment]
Wut? Now they are there.

**Comment by LosD** [comment]
Ah, there's a block in the middle where they are missing, and the Conversation tab preview doesn't show the missing EOL character :)

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+import java.util.List;
+import java.util.Map;
+
+import org.datacleaner.monitor.server.wizard.shared.ReferenceDataHelper;
+import org.datacleaner.monitor.server.wizard.shared.datastore.DatastorePage1;
+import org.datacleaner.monitor.server.wizard.shared.datastore.DatastoreWizardSession;
+import org.datacleaner.monitor.shared.model.DCUserInputException;
+import org.datacleaner.monitor.wizard.WizardPageController;
+
+final class DatastoreDictionaryReferenceDataPage1 extends DatastorePage1 {
```
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java]: Can't we use something more descriptive than page1, page2, page3 etc.?

File: engine/core/src/main/java/org/datacleaner/reference/ReferenceDataCatalogImpl.java [hunk 9]
```diff
@@ -109,6 +109,17 @@ public Dictionary getDictionary(String name) {
 		return null;
 	}
 
+	private boolean removeItem(Collection collection, String name) {
```
Comment (arjansh) [inline engine/core/src/main/java/org/datacleaner/reference/ReferenceDataCatalogImpl.java]: This method isn't used. Can it be removed?

Comment (LosD) [inline engine/core/src/main/java/org/datacleaner/reference/ReferenceDataCatalogImpl.java]: Maybe revert  the whole file then. as the only changes would then be the replace-with-diamond changes.

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java (hunk 8 above)
Comment (jhorcicka) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java]: We certainly can. What exactly do have on your mind? I can imagine: 
```
DatastoreDictionaryReferenceDataNamePage
DatastoreDictionaryReferenceDataSchemaPage
DatastoreDictionaryReferenceDataTablePage 
DatastoreDictionaryReferenceDataColumnPage
```
 but here I am missing the order. Perhaps I can leave the numbers: 
```
DatastoreDictionaryReferenceDataNamePage1
DatastoreDictionaryReferenceDataSchemaPage2
DatastoreDictionaryReferenceDataTablePage3
DatastoreDictionaryReferenceDataColumnPage4
```
but that makes me thinking that there might be something like DatastoreDictionaryReferenceDataNamePage2, DatastoreDictionaryReferenceDataNamePage3, ... as well which is not the case. 

So, what about: 
```
DatastoreDictionaryReferenceDataPage1Name
DatastoreDictionaryReferenceDataPage2Schema
DatastoreDictionaryReferenceDataPage3Table
DatastoreDictionaryReferenceDataPage4Column
```
?

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/regexswap/RegexSwapStringPatternReferenceDataWizardSession.java [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+import org.datacleaner.reference.regexswap.RegexSwapClient;
+import org.datacleaner.reference.regexswap.RegexSwapStringPattern;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.w3c.dom.Element;
+
+final class RegexSwapStringPatternReferenceDataWizardSession extends AbstractReferenceDataWizardSession {
+
+    private static final Logger logger =
+            LoggerFactory.getLogger(RegexSwapStringPatternReferenceDataWizardSession.class);
```
Comment (arjansh) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/regexswap/RegexSwapStringPatternReferenceDataWizardSession.java]: The logger is not used. Can be removed.

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java [hunk 11]
```diff
@@ -0,0 +1,91 @@
...
+import org.datacleaner.monitor.wizard.referencedata.ReferenceDataWizardContext;
+import org.datacleaner.reference.SimpleStringPattern;
+import org.datacleaner.reference.StringPattern;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.w3c.dom.Element;
+
+final class SimpleStringPatternReferenceDataWizardSession extends AbstractReferenceDataWizardSession {
+
+    private static final Logger logger = LoggerFactory.getLogger(SimpleStringPatternReferenceDataWizardSession.class);
```
Comment (arjansh) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java]: The logger is not used. Can be removed.

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java [hunk 12]
```diff
@@ -0,0 +1,91 @@
...
+    @Override
+    public Integer getPageCount() {
+        return 1;
+    }
+
+    @Override
+    protected Element getUpdatedReferenceDataSubSection(final DocumentBuilder documentBuilder) {
+        final Resource resource = getWizardContext().getTenantContext().getConfigurationFile().toResource();
+        final DomConfigurationWriter writer = new DomConfigurationWriter(resource);
+        final Element stringPatternsElement = writer.getStringPatternsElement();
```
Comment (arjansh) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java]: The three lines of code used to retrieve the stringPatternsElement seem to be copy/pasted from the RegexSwapStringPatternReferenceDataWizardSession class. Maybe extract these into a separate method on the AbstractReferenceDataWizardSession called getStringPatternsElement() which can be invoked from both classes.

File: monitor/extensions/referencedata-wizards/src/main/resources/org/datacleaner/monitor/server/wizard/dictionary/simple/SimpleDictionaryReferenceDataPage.html [hunk 13]
```diff
@@ -0,0 +1,29 @@
+<div style="min-height: 200px; background-repeat: no-repeat; background-position: bottom right; ">
+    <form action="repository/demo/jobs/multiple_upload" method="post" enctype="multipart/form-data">
```
Comment (arjansh) [inline monitor/extensions/referencedata-wizards/src/main/resources/org/datacleaner/monitor/server/wizard/dictionary/simple/SimpleDictionaryReferenceDataPage.html]: The path "repository/demo/jobs/multiple_upload" will only work in the default DC Monitor setup where we use the "demo" tenant. If you configure DC Monitor to run on another tenant (or set up a multi tenant config) things will break down.

**Comment by arjansh** [comment]
The are quite some test classes where you do "import static org.junit.Assert.*;", instead of specific imports.

**Comment by LosD** [comment]
It's the default in IntelliJ if there is 3 or more static imports for the same class... Makes sense to me, but we can increase it.

**Comment by arjansh** [comment]
If you all like it that way, just keep it that way.

File: monitor/services/src/main/java/org/datacleaner/monitor/server/dao/ReferenceDataDaoImpl.java [hunk 14]
```diff
@@ -0,0 +1,214 @@
...
+import org.w3c.dom.NodeList;
+import org.xml.sax.InputSource;
+
+/**
+ * Default implementation of {@link ReferenceDataDao}. 
+ */
+@Component
+public class ReferenceDataDaoImpl implements ReferenceDataDao {
+
+    private static final Logger logger = LoggerFactory.getLogger(ReferenceDataDaoImpl.class);
```
Comment (arjansh) [inline monitor/services/src/main/java/org/datacleaner/monitor/server/dao/ReferenceDataDaoImpl.java]: Another unused logger.

**Comment by LosD** [comment]
Might still be an issue: Would Eclipse "optimize" them back to individual static imports? In that case, we might want to keep the least ping-pong-y setting.

**Comment by arjansh** [comment]
It does that when I do "organize imports" in Eclipse. Maybe that can be configured however.

File: monitor/ui/pom.xml [hunk 15]
```diff
@@ -26,6 +27,9 @@
 						<goals>
 							<goal>compile</goal>
 						</goals>
+						<configuration>
+							<sourceLevel>1.7</sourceLevel> <!-- 1.6 or 1.7 -->
```
Comment (arjansh) [inline monitor/ui/pom.xml]: See if it really necessary to set the sourceLevel to 1.7

File: monitor/ui/src/main/webapp/datastores.xhtml [hunk 16]
```diff
@@ -79,6 +79,16 @@
 									<span>Download</span>
 								</button>
 							</h:panelGroup>
+							<h:panelGroup
+								rendered="#{ds.fileDatastore and user.configurationEditor}">
+<!-- 									onclick="window.location='repository/#{tenantContext.tenantId}/datastores/#{ds.name}.download'" -->
```
Comment (arjansh) [inline monitor/ui/src/main/webapp/datastores.xhtml]: Please remove the out-commented line.

**Comment by arjansh** [comment]
I'm done with code reviewing this issue. For me the only real showstopper seems the hard-coded "repository/demo/jobs/multiple_upload" path, as mentioned somewhere earlier.

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java (hunk 12 above)
Comment (jhorcicka) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/stringpattern/simple/SimpleStringPatternReferenceDataWizardSession.java]: 1) AbstractReferenceDataWizardSession is used for all types of reference data, not only string patterns. So, I don't think it's a good idea to put code specific for only some (2 out of 10 in this case) sub-classes to its parent. 

2) "DomConfigurationWriter writer" is also needed later for externalization so its instantiation would be needed in those two classes. 

But creation of that "writer" is the same for all sub types so I will create "DomConfigurationWriter getWriter()" in the parent and use this in all sub-classes.

File: monitor/extensions/referencedata-wizards/src/main/resources/org/datacleaner/monitor/server/wizard/dictionary/simple/SimpleDictionaryReferenceDataPage.html (hunk 13 above)
Comment (jhorcicka) [inline monitor/extensions/referencedata-wizards/src/main/resources/org/datacleaner/monitor/server/wizard/dictionary/simple/SimpleDictionaryReferenceDataPage.html]: Actually, this is a forgotten artifact. It is not used. I will remove it. Thanks for noticing it. ;-)

File: monitor/ui/pom.xml (hunk 15 above)
Comment (jhorcicka) [inline monitor/ui/pom.xml]: Now I remember why this is here. It's not necessary for functionality but "the strange thing" is that it is not 1.8. Only 1.6. and 1.7. are allowed. That's why I left it there.

Comment (LosD) [inline monitor/ui/pom.xml]: Might be an old version of the compiler plugin?

Comment (LosD) [inline monitor/ui/pom.xml]: Oh, it's the GWT Maven plugin. I'm not even sure they support Java 8?

Comment (LosD) [inline monitor/ui/pom.xml]: Supported from 2.8.0

Comment (jhorcicka) [inline monitor/ui/pom.xml]: Now we use 2.7.0 which is the latest "stable" release. There's 2.8.0-* as beta and release candidates.

Comment (LosD) [inline monitor/ui/pom.xml]: Yeah, no need to get funky with RCs :)

File: monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java (hunk 8 above)
Comment (LosD) [inline monitor/extensions/referencedata-wizards/src/main/java/org/datacleaner/monitor/server/wizard/dictionary/datastore/DatastoreDictionaryReferenceDataPage1.java]: The order is not really relevant when reading the code. Keeping the numbers would also mean that reordering would mean new classnames.

I'd kill the numbers entirely.

**Comment by LosD** [comment]
Besides naming, LGTM

**Comment by jhorcicka** [comment]
Wait with the merge, I'll change the names.

**Comment by jhorcicka** [comment]
@LosD: *Page<Number> classes were renamed.

**Comment by LosD** [comment]
LGTM!
