### PR TITLE
Fix backwards compatibility issue in plain search/replace transformer

### LINKED ISSUE #1284: Plain search/replace transformer is not backwards compatible
In the context of https://github.com/datacleaner/DataCleaner/pull/1149 the `Plain search/replace transformer` has been refactored and jobs configured to use that transformer configured in DataCleaner versions older than 5.0 can no longer be loaded in DataCleaner 5.0. If you try to load such a job, you get a `No such property: Search string` error.

You should however be able to load the job without problems and it should fix/upgrade its own configuration to comply with its 5.0 variant.

### PR DESCRIPTION
**Pull request by arjansh**
Fixes #1284.

Added some logic to the JaxbJobReader#applyProperties method which checks if a property has been removed from the component which is being read, stores these values and uses these to process the removed properties, i.e. assign their values to another newly introduced property if necessary.

Implemented this logic specifically for the PlainSearchReplaceTransformer from which the "Search string" and "Replacement string" properties have been removed in favor of a "Replacements" property.

### CODE REVIEW

**Comment by LosD** [comment]
Code looks good, but a quick test loading an old job would be nice.

File: engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java [hunk 1]
```diff
@@ -878,38 +879,49 @@ private void applyProperties(final ComponentBuilder builder,
         if (configuredPropertiesType != null) {
             final List<Property> properties = configuredPropertiesType.getProperty();
             final ComponentDescriptor<?> descriptor = builder.getDescriptor();
+
+            Map<String, String> removedProperties = new HashMap<>();
```
Comment (LosD) [inline engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java]: final
